### ISSUE TITLE
[3 basic questions]

### ISSUE THREAD

**Issue by zapahacks** [engle2192/PoGoMap-GUI#10]
Thanks for this, I finally have the map working on my pc

I have 3 questions:
1. Is there anyway to change the location/coordinates where the program validates if your accounts are active/banned? (like, I want the accounts to only log in the area where I am running the map, and not a the default location 40...., 74...) I just think it could help the accounts not to get banned because of different countries log info.
2. Is there anyway to set the account creating to an specific country?, like I want all my accounts to be from the country where I am scanning....
3. Does having more accounts translate into having a bigger area scanned?
4. What does "2016-09-17 12:50:19,789 [ search-worker-2][        search][    INFO] Early for -25.....,-49.....; waiting 321s..." means and why do I get this error

**Comment by Go2Engle** [comment]
1 - 2. Currently with the GUI there is no way to change the location of the created and checked accounts. If you run the commands manually you can do this. Since you have brought this up I just thought of an easy way I can make it so it uses your inputted location and can add this in coming updates.
1. No more accounts does not equal larger area scanned. The more accounts you have will translate into faster scanning times from my experience. To largen the area scanned just up the step limit.
2. Not sure what this error is. You may want to look on the official pokemonGo-Map github for that answer.
